default:
  image: olimex/olinuxino-overlays

stages:
  - test
  - build
  - deploy

test:
  only:
    - /^upstream/
  script:
    - cd test && bash bootstrap.sh
  stage: test

build:
  artifacts:
    name: "$CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA"
    paths:
      - $CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA/*
    when: on_success
  except:
    - /^upstream/
  script:
    - git checkout -B "$CI_BUILD_REF_NAME" "$CI_BUILD_REF"
    - git fetch origin +refs/heads/upstream:refs/tags/upstream
    - gbp export-orig --upstream-tree=origin/upstream
    - tar -xvf ../olinuxino-overlays*.orig.tar.gz --skip-old-files --strip 1 -C ./
    - dpkg-buildpackage --post-clean --no-sign -i -I
    - mkdir $CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA && cp -vf ../olinuxino-overlays_*.* ./$CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA/
  stage: build

deploy:
  script:
    - reprepro -b /var/www/html/staging/ --ignore=wrongdistribution include buster $CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA/*.changes
  tags:
    - deploy
  when: manual
