default:
  image: olimex/olinuxino-overlays

stages:
  - test
  - build
  - deploy

test:
  script:
    - make test
  stage: test
  when: manual

build:
  artifacts:
    paths:
      - $CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA/*
  script:
    - git checkout -B "$CI_BUILD_REF_NAME" "$CI_BUILD_REF"
    - sed -i "s/BUILD_DATE/$(date +%Y%m%d%H%M%S)/g" debian/changelog
    - dpkg-buildpackage --post-clean -uc -us
    - mkdir $CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA && cp -vf ../olinuxino-overlays_*.* $CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA/
  stage: build

deploy:staging:
  script:
    - |
      for repo in $REPOS ; do
        reprepro -b /var/www/html/staging --ignore=wrongdistribution include $repo $CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA/*.changes
      done
  stage: deploy
  tags:
    - deploy

deploy:repository:
  script:
    - |
      for repo in $REPOS ; do
        reprepro -b /var/www/html/repository --ignore=wrongdistribution include $repo $CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA/*.changes
      done
  stage: deploy
  tags:
    - deploy
  when: manual
